language: rust
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
deploy:
  provider: cargo
  on:
    tags: true
    branch: master
    rust: stable
  token:
    secure: HkkBqXFxjxySKZUKNkt77c8oOqtR/JhYblK+wIZ/tNuZF/ROwm1wZnkO5O5LL39DUXMgX47ieAa2FytceJiZSAobUp5/GY9jif3DHMPOgeGnP+7DJwGsO9GJl1jr22O5u55kIZEPjmX8qWgnpYyZ4kXfBRDXMYqz1ur9NtGtGVpQOb9rXp+ADU+of6u3Z1iFzyaG2gh9XfkXCJHch7K/F3MzjqEtMJ+rVKYsraYvf84gNUCygLYLzLnIC5RYepLRNArRwuM5IYwOlyo39+m8x9k+wEzI9n04CoDMKPbkE0aIHkkdLBXT+edPvYaoatDS6wTWG0jjmEeHi0LwhwP8o8FDqjThnwCHRrOoX0z5cn92rM7SJMHMAVMt2c+R6UNhqwceqwWxo18a/LkCfrf6XoWRct8krh4nvHTN+4zii+Q8dQaKCoDHh9bnHa/9dpVaBj0SZWWQPm4m4/CNWawWZcSRCv5dT/OZbk5lppzm60X68Gs+bx/ty+Y2Xk4bHQlKcrrWnPGjHeuodk11hkOzAxsSbgPjTTKbCqIPFp99SH8nrPRfTsxHePiYvRbw9iXev3ljwS84g0MRrp2C/dtcWDnamQJvHZPuU0I8Q6GqHeH48WF822kAF5igr0Ry4rJj+e8e/t/Tv7FFROv1FC5mPFo+1gQ5yXC2ntYuTAAzwKU=
notifications:
  slack:
    secure: aHnuAltx26XrPjUJ0Grj8MgmBYyx8+QKmRko7OiDcPWnsMg6d02BQk1DnXHYeyQe/sBe5gdDMeOHuy0I1tH5niAYoF9RenltKDjaVIlvRKrqtL6gLeYRF2585+xR4PKhxmYUKxGiurfSpLnhz0PCzzPWgWm0BHYW/rt0jCNk1vgzNNeqNqm3Jn/+kMZ2nUPIjx75KF7vJLCsOFM1PFVPgaikGGKVzGfnonakBmWsR01omREdjsi52y+OoM2PNil+J1kTkccT9ryOqCuUceUeWVDnwDnH5c+2eWd3N3xC5SKpRg/meevV3iNXTwNpmY6vC1CSBP1wuMRlZx1CMZItBseoV+j/Ng4y9dTW+WHQJoBGvu5UH6B80NXJj60xmuMOgY/O+qALq87rNIEn6FE6qkqfZnSBMdk2bCw+MADIfz+Rz5rfUnOCJQi/RNQNfmMTzBASxzaHRPTg7WQcTAC4DTxU1xTcKqZSaU3j6FFkqWtlJH4+ebZrsXaX/rPPYYSCgLQhQhZO0+pyfXT36iPABUYujW3/UYOHqf2Lx7HgbApdX4EAD3bFf+rAZOytUl70AYygoomKBZDIy4mkMgC5t8bsEdTpedJrWuCLxNNdIPGlfPIZD6w4p09FlSVRsy2JhlZCvas5NnDDpQZFU+SufFKMEQwgH7KU6dvNyJdPMDQ=
