[package]
name = "pusoy_dos2"
description = "pusoy dos lib"
license = "MIT"
version = "0.1.2"
authors = ["Ben Brunton <benbrunton@hotmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6"
nanoid = "0.1.3"
wasm-bindgen = "0.2"
